set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cathodes[0]}]
set_property PACKAGE_PIN L18 [get_ports {o_cathodes[6]}]
set_property PACKAGE_PIN T11 [get_ports {o_cathodes[5]}]
set_property PACKAGE_PIN P15 [get_ports {o_cathodes[4]}]
set_property PACKAGE_PIN K13 [get_ports {o_cathodes[3]}]
set_property PACKAGE_PIN K16 [get_ports {o_cathodes[2]}]
set_property PACKAGE_PIN R10 [get_ports {o_cathodes[1]}]
set_property PACKAGE_PIN T10 [get_ports {o_cathodes[0]}]
set_property PACKAGE_PIN H15 [get_ports {o_cathodes[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_anodes[0]}]
set_property PACKAGE_PIN U13 [get_ports {o_anodes[7]}]
set_property PACKAGE_PIN K2 [get_ports {o_anodes[6]}]
set_property PACKAGE_PIN T14 [get_ports {o_anodes[5]}]
set_property PACKAGE_PIN P14 [get_ports {o_anodes[4]}]
set_property PACKAGE_PIN J14 [get_ports {o_anodes[3]}]
set_property PACKAGE_PIN T9 [get_ports {o_anodes[2]}]
set_property PACKAGE_PIN J18 [get_ports {o_anodes[1]}]
set_property PACKAGE_PIN J17 [get_ports {o_anodes[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_switches[0]}]
set_property PACKAGE_PIN R13 [get_ports {i_switches[7]}]
set_property PACKAGE_PIN U18 [get_ports {i_switches[6]}]
set_property PACKAGE_PIN J15 [get_ports {i_switches[0]}]
set_property PACKAGE_PIN L16 [get_ports {i_switches[1]}]
set_property PACKAGE_PIN M13 [get_ports {i_switches[2]}]
set_property PACKAGE_PIN R15 [get_ports {i_switches[3]}]
set_property PACKAGE_PIN R17 [get_ports {i_switches[4]}]
set_property PACKAGE_PIN T18 [get_ports {i_switches[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_btnReset]
set_property IOSTANDARD LVCMOS33 [get_ports i_btnStep]
set_property IOSTANDARD LVCMOS33 [get_ports i_swEnableBreakpoint]
set_property IOSTANDARD LVCMOS33 [get_ports i_swInstrNCycle]
set_property IOSTANDARD LVCMOS33 [get_ports i_swStepNRun]
set_property PACKAGE_PIN C12 [get_ports i_btnReset]
set_property PACKAGE_PIN N17 [get_ports i_btnStep]
set_property PACKAGE_PIN V10 [get_ports i_swEnableBreakpoint]
set_property PACKAGE_PIN U11 [get_ports i_swInstrNCycle]
set_property PACKAGE_PIN U12 [get_ports i_swStepNRun]

create_clock -period 10.000 -name i_clk100 -waveform {0.000 5.000} [get_ports i_clk100]
set_input_delay -clock [get_clocks i_clk100] -min -add_delay 0.000 [get_ports {i_switches[*]}]
set_input_delay -clock [get_clocks i_clk100] -max -add_delay 2.000 [get_ports {i_switches[*]}]

set_false_path -from [get_pins -hierarchical -regexp inst_datapath/inst_memory/ram.*]
set_false_path -from [get_pins -hierarchical -regexp inst_datapath/control_bd_i/instrDecode.*]
set_false_path -to [get_pins -hierarchical -regexp .*inst_datapath/inst_memory/ram.*]
set_false_path -from [get_ports -regexp .*i_switches.*]
set_false_path -to [get_pins -hierarchical -regexp .*inst_datapath/inst_memory/instrRom.*]

set_property IOSTANDARD LVCMOS33 [get_ports i_clk100]
set_property PACKAGE_PIN E3 [get_ports i_clk100]
