# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io_constraint.xdc

# Block Designs: bd/memory_bd/memory_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_bd || ORIG_REF_NAME==memory_bd} -quiet] -quiet

# IP: bd/memory_bd/ip/memory_bd_blk_mem_gen_0_0/memory_bd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==memory_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/memory_bd/ip/memory_bd_blk_mem_gen_0_1/memory_bd_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_bd_blk_mem_gen_0_1 || ORIG_REF_NAME==memory_bd_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/memory_bd/ip/memory_bd_ram_0/memory_bd_ram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_bd_ram_0 || ORIG_REF_NAME==memory_bd_ram_0} -quiet] -quiet

# IP: bd/memory_bd/ip/memory_bd_memory_0_0/memory_bd_memory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_bd_memory_0_0 || ORIG_REF_NAME==memory_bd_memory_0_0} -quiet] -quiet

# Block Designs: bd/control_bd/control_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==control_bd || ORIG_REF_NAME==control_bd} -quiet] -quiet

# IP: bd/control_bd/ip/control_bd_xlconstant_0_0/control_bd_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==control_bd_xlconstant_0_0 || ORIG_REF_NAME==control_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/control_bd/ip/control_bd_instrRom_0/control_bd_instrRom_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==control_bd_instrRom_0 || ORIG_REF_NAME==control_bd_instrRom_0} -quiet] -quiet

# IP: bd/control_bd/ip/control_bd_control_0_0/control_bd_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==control_bd_control_0_0 || ORIG_REF_NAME==control_bd_control_0_0} -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/bd/memory_bd/memory_bd_ooc.xdc

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/bd/control_bd/control_bd_ooc.xdc
