# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niklas/dev/EDiC/vivado/EDiC.srcs/sources_1/bd/memory_bd/ip/memory_bd_ram_0/memory_bd_ram_0.xci
# IP: The module: 'memory_bd_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/bd/memory_bd/ip/memory_bd_ram_0/memory_bd_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_bd_ram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/niklas/dev/EDiC/vivado/EDiC.srcs/sources_1/bd/memory_bd/ip/memory_bd_ram_0/memory_bd_ram_0.xci
# IP: The module: 'memory_bd_ram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/bd/memory_bd/ip/memory_bd_ram_0/memory_bd_ram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_bd_ram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
