# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.runs/synth_1/board_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.cache/wt [current_project]
set_property parent.project_path C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/microCodeRom.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom_9600.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom_9600_8_s1.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom_9600_random_delay.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom_9600_random_delay2.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom_19200_xoff.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom_19200_fill.coe
add_files c:/Users/niklas/dev/Tigris/EDiC/memory_files/instructionRom_19200_fill_fix.coe
read_verilog -library xil_defaultlib {
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/displayDriver.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/generated.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic28C256.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic5082_7340.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x04.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x08.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x14.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x151.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x153.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x157.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x245.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x273.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x32.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x374.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x521.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x540.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x825.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x86.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/ic74x867.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/icAS6C4008.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/icBerg10.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/icBerg26.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/icBerg40.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/icds1813.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/tristatenet.v
  C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/board_top.v
}
read_ip -quiet c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.srcs/sources_1/ip/instructionRom/instructionRom.xci
set_property used_in_implementation false [get_files -all c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/instructionRom/instructionRom_ooc.xdc]

read_ip -quiet c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.srcs/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz.xci
set_property used_in_implementation false [get_files -all c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz.xdc]
set_property used_in_implementation false [get_files -all c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz_ooc.xdc]

read_ip -quiet c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.srcs/sources_1/ip/as6c4008_55pcn_mem/as6c4008_55pcn_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/as6c4008_55pcn_mem/as6c4008_55pcn_mem_ooc.xdc]

read_ip -quiet c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.srcs/sources_1/ip/microCodeRom/microCodeRom.xci
set_property used_in_implementation false [get_files -all c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/microCodeRom/microCodeRom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/io_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/_src/io_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.srcs/utils_1/imports/synth_1/board_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top board_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef board_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file board_top_utilization_synth.rpt -pb board_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
