webtalk_init -webtalk_dir /home/niklas/dev/EDiC/vivado/EDiC.sim/sim_1/behav/xsim/xsim.dir/tb_datapath_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Nov  6 12:15:58 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6a16f4f7-6cb8-4483-bbd5-4087648f8eac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "352091bf80ab4faaa03539bdb71c39e3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3700X 8-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3945.424 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.64_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124384_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3318507336 -regid "" -xml /home/niklas/dev/EDiC/vivado/EDiC.sim/sim_1/behav/xsim/xsim.dir/tb_datapath_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/niklas/dev/EDiC/vivado/EDiC.sim/sim_1/behav/xsim/xsim.dir/tb_datapath_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/niklas/dev/EDiC/vivado/EDiC.sim/sim_1/behav/xsim/xsim.dir/tb_datapath_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
