# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.srcs/sources_1/ip/ila_U39/ila_U39.xci
# IP: The module: 'ila_U39' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/ila_U39/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_U39'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/ila_U39/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_U39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/ila_U39/ila_U39_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_U39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.srcs/sources_1/ip/ila_U39/ila_U39.xci
# IP: The module: 'ila_U39' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/ila_U39/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_U39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/ila_U39/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_U39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/ila_U39/ila_U39_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_U39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
