# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.srcs/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz.xci
# IP: The module: 'clk_wiz_5Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5Mhz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.srcs/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz.xci
# IP: The module: 'clk_wiz_5Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/sim_ttl/vivado/EDiC-TTL.gen/sources_1/ip/clk_wiz_5Mhz/clk_wiz_5Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_5Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
