# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niklas/dev/8bitCpu/vivado/8bitCPU.srcs/sources_1/ip/microCodeRom/microCodeRom.xci
# IP: The module: 'microCodeRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/8bitCpu/vivado/8bitCPU.srcs/sources_1/ip/microCodeRom/microCodeRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microCodeRom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/niklas/dev/8bitCpu/vivado/8bitCPU.srcs/sources_1/ip/microCodeRom/microCodeRom.xci
# IP: The module: 'microCodeRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/8bitCpu/vivado/8bitCPU.srcs/sources_1/ip/microCodeRom/microCodeRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microCodeRom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
