# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niklas/dev/EDiC/vivado/EDiC.srcs/sources_1/ip/dbgIla/dbgIla.xci
# IP: The module: 'dbgIla' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/ip/dbgIla/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbgIla'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/ip/dbgIla/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbgIla'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/ip/dbgIla/dbgIla_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbgIla'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/niklas/dev/EDiC/vivado/EDiC.srcs/sources_1/ip/dbgIla/dbgIla.xci
# IP: The module: 'dbgIla' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/ip/dbgIla/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbgIla'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/ip/dbgIla/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbgIla'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niklas/dev/EDiC/vivado/EDiC.gen/sources_1/ip/dbgIla/dbgIla_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dbgIla'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
