# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/niklas/dev/EDiC/sim_ttl/_src/io_constraints.xdc

# IP: ip/instructionRom/instructionRom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==instructionRom || ORIG_REF_NAME==instructionRom} -quiet] -quiet
