# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/niklas/dev/EDiC/sim_ttl/_src/io_constraints.xdc

# IP: ip/clk_wiz_5Mhz/clk_wiz_5Mhz.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_5Mhz || ORIG_REF_NAME==clk_wiz_5Mhz} -quiet] -quiet
