# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.srcs/sources_1/ip/microCodeRom/microCodeRom.xci
# IP: The module: 'microCodeRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/microCodeRom/microCodeRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microCodeRom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.srcs/sources_1/ip/microCodeRom/microCodeRom.xci
# IP: The module: 'microCodeRom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/niklas/dev/Tigris/EDiC/sim_ttl/vivado_win/EDiC-TTL-Win.gen/sources_1/ip/microCodeRom/microCodeRom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microCodeRom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
