# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niklas/dev/MEDiC/vivado/MEDiC.srcs/sources_1/bd/control_bd/ip/control_bd_instrRom_0/control_bd_instrRom_0.xci
# IP: The module: 'control_bd_instrRom_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/MEDiC/vivado/MEDiC.gen/sources_1/bd/control_bd/ip/control_bd_instrRom_0/control_bd_instrRom_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'control_bd_instrRom_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/niklas/dev/MEDiC/vivado/MEDiC.srcs/sources_1/bd/control_bd/ip/control_bd_instrRom_0/control_bd_instrRom_0.xci
# IP: The module: 'control_bd_instrRom_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niklas/dev/MEDiC/vivado/MEDiC.gen/sources_1/bd/control_bd/ip/control_bd_instrRom_0/control_bd_instrRom_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'control_bd_instrRom_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
